name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # need this for OIDC
      contents: read
    strategy:
      matrix:
        include:
          - tox-env: py311-django42
            python-version: '3.11'
          - tox-env: py311-django52
            python-version: '3.11'
          - tox-env: py312-django42
            python-version: '3.12'
          - tox-env: py312-django52
            python-version: '3.12'
          - tox-env: quality
            python-version: '3.12'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install requirements
        run: pip install -r requirements/ci.txt
      - name: Run tox
        env:
          TOXENV: ${{ matrix.tox-env }}
        run: tox
